apiVersion: v1
kind: Service
metadata:
  name: ets-noc-lb
  namespace: ets-noc
spec:
  type: LoadBalancer
  selector:
    app: ets-noc-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ets-noc-ingress
  namespace: ets-noc
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "ets-noc-ip"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - noc.etsusa.com
    secretName: ets-noc-tls
  rules:
  - host: noc.etsusa.com
    http:
      paths:
      - path: /api/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: ets-noc-api
            port:
              number: 8080
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: ets-noc-frontend
            port:
              number: 80
